#! /bin/bash
[ -v BASH ] || {
	echo Please run this project on bash!
	exit 1
}
[ "${BASH_VERSINFO:-0}" -lt 5 ] && ! [ -v MCEDITOR_ignore_bash_version ] && {
	echo "The bash version needs to be 5+(currect $BASH_VERSION)"
	echo To ignore this, set MCEDITOR_ignore_bash_version
	echo WARN: this may cause CRITICAL PROBLEMS even destroy ur file!
	exit 1
}
jq --version 2>&1 >/dev/null || {
	echo 'This project depends on jq from snap/deb jq'
	read -r -p 'Do you want to install?(y)' insjq
	[[ "$insjq" == [yY] ]] && {
		sudo apt install jq
	}
	exit 1
}
unset	MCEDITOR_INC_editor		MCEDITOR_INC_world		MCEDTIOR_INC_option_list \
	MCEDITOR_INC_input		MCEDITOR_INC_map		MCEDITOR_INC_hardness \
	MCEDITOR_INC_print		MCEDITOR_INC_block		MCEDITOR_INC_enitity \
	MCEDITOR_INC_espmap		MCEDITOR_INC_block_proportions	MCEDITOR_INC_block_piston \
	MCEDITOR_INC_heap		MCEDITOR_INC_print_progress	MCEDITOR_INC_container \
	MCEDITOR_INC_argument		MCEDITOR_INC_dimension		MCEDITOR_INC_fifo \
	MCEDITOR_INC_print_window	NCEDITOR_INC_save		MCEDITOR_INC_world_list \
	MCEDITOR_INC_base_check		MCEDITOR_INC_base_str
ldir="`dirname "$0"`"
[ "$ldir" ] || {
	echo 'What happened I even cannot find the executable file awa'
	sleep 3
	exit 1
}
export dirp="$ldir"/run
export dirlib="$ldir"/lib
export dirlog="$ldir"/log
export dirtmp="$ldir"/tmp
export dirassets="$ldir"/assets
export dirgame="$ldir"
mkdir -p "$dirlog" "$dirtmp"
MCEDITOR_dbgl=`echo -n "$dbgl" | jq -crM .mcide`
[[ "$MCEDITOR_dbgl" != [0-9] ]] && MCEDITOR_dbgl=0
{
	logfile="$dirlog/`date '+%F/%T'`#$$.log"
	rm "$dirlog"/latest.log
	ln -s "$logfile" "$dirlog"/latest.log
	mkdir -p "${logfile%/*}"
       	exec 2> "$logfile"
}
echo "Using tmp dictionary $dirtmp" >&2
[ "$MCEDITOR_dbgl" -ge 2 ] && {
	echo "Current debug level: $MCEDITOR_dbgl"
	sleep 0.3
}
. "$dirp"/editor.sh
editormain "$@"
